---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: store-composition
spec:
  compositeTypeRef:
    apiVersion: adolfosilva.dev/v1alpha1
    kind: Store
  patchSets:
    - name: metadata
      patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
    - name: region
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
  resources:
    - name: bucket
      base:
        apiVersion: s3.aws.upbound.io/v1beta2
        kind: Bucket
        spec:
          forProvider: {}
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: metadata
        - type: PatchSet
          patchSetName: region
    - name: queue
      base:
        apiVersion: sqs.aws.upbound.io/v1beta1
        kind: Queue
        spec:
          forProvider: {}
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: metadata
        - type: PatchSet
          patchSetName: region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.id
          toFieldPath: spec.forProvider.name
