apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: store.adolfosilva.dev
spec:
  group: adolfosilva.dev
  names:
    kind: Store
    plural: stores
  claimNames:
    kind: StoreClaim
    plural: storeclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                type: string
              generatedName:
                type: string
            required:
              - region
              - generatedName
