---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: stores.adolfosilva.dev
spec:
  group: adolfosilva.dev
  names:
    kind: Store
    plural: stores
  claimNames:
    kind: StoreClaim
    plural: storeclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                  description: Name of the bucket
                region:
                  type: string
                  description: AWS Region
              required:
                - id
                - region
